/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GulfFlowEscrowPolicy {
  export type DealStruct = {
    buyer: AddressLike;
    supplier: AddressLike;
    invoiceAmountUsdc6: BigNumberish;
    advanceAmountUsdc6: BigNumberish;
    documentHash: BytesLike;
    invoiceRef: string;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type DealStructOutput = [
    buyer: string,
    supplier: string,
    invoiceAmountUsdc6: bigint,
    advanceAmountUsdc6: bigint,
    documentHash: string,
    invoiceRef: string,
    status: bigint,
    createdAt: bigint
  ] & {
    buyer: string;
    supplier: string;
    invoiceAmountUsdc6: bigint;
    advanceAmountUsdc6: bigint;
    documentHash: string;
    invoiceRef: string;
    status: bigint;
    createdAt: bigint;
  };
}

export interface GulfFlowEscrowPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveDocuments"
      | "cancelDeal"
      | "completeDeal"
      | "deals"
      | "getDeal"
      | "lockDeal"
      | "releaseAdvance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdvanceReleased"
      | "DealCancelled"
      | "DealCompleted"
      | "DealLocked"
      | "DocumentsApproved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveDocuments",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDeal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeDeal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "deals", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getDeal", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "lockDeal",
    values: [
      BytesLike,
      AddressLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseAdvance",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseAdvance",
    data: BytesLike
  ): Result;
}

export namespace AdvanceReleasedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    supplier: AddressLike,
    advanceAmountUsdc6: BigNumberish
  ];
  export type OutputTuple = [
    dealId: string,
    supplier: string,
    advanceAmountUsdc6: bigint
  ];
  export interface OutputObject {
    dealId: string;
    supplier: string;
    advanceAmountUsdc6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCancelledEvent {
  export type InputTuple = [dealId: BytesLike];
  export type OutputTuple = [dealId: string];
  export interface OutputObject {
    dealId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCompletedEvent {
  export type InputTuple = [dealId: BytesLike];
  export type OutputTuple = [dealId: string];
  export interface OutputObject {
    dealId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealLockedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    buyer: AddressLike,
    supplier: AddressLike,
    invoiceRef: string,
    invoiceAmountUsdc6: BigNumberish,
    advanceAmountUsdc6: BigNumberish,
    documentHash: BytesLike
  ];
  export type OutputTuple = [
    dealId: string,
    buyer: string,
    supplier: string,
    invoiceRef: string,
    invoiceAmountUsdc6: bigint,
    advanceAmountUsdc6: bigint,
    documentHash: string
  ];
  export interface OutputObject {
    dealId: string;
    buyer: string;
    supplier: string;
    invoiceRef: string;
    invoiceAmountUsdc6: bigint;
    advanceAmountUsdc6: bigint;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentsApprovedEvent {
  export type InputTuple = [dealId: BytesLike, documentHash: BytesLike];
  export type OutputTuple = [dealId: string, documentHash: string];
  export interface OutputObject {
    dealId: string;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GulfFlowEscrowPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): GulfFlowEscrowPolicy;
  waitForDeployment(): Promise<this>;

  interface: GulfFlowEscrowPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveDocuments: TypedContractMethod<
    [dealId: BytesLike, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelDeal: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  completeDeal: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  deals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, string, bigint, bigint] & {
        buyer: string;
        supplier: string;
        invoiceAmountUsdc6: bigint;
        advanceAmountUsdc6: bigint;
        documentHash: string;
        invoiceRef: string;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getDeal: TypedContractMethod<
    [dealId: BytesLike],
    [GulfFlowEscrowPolicy.DealStructOutput],
    "view"
  >;

  lockDeal: TypedContractMethod<
    [
      dealId: BytesLike,
      supplier: AddressLike,
      invoiceRef: string,
      invoiceAmountUsdc6: BigNumberish,
      advanceAmountUsdc6: BigNumberish,
      documentHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  releaseAdvance: TypedContractMethod<
    [dealId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveDocuments"
  ): TypedContractMethod<
    [dealId: BytesLike, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelDeal"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeDeal"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, string, bigint, bigint] & {
        buyer: string;
        supplier: string;
        invoiceAmountUsdc6: bigint;
        advanceAmountUsdc6: bigint;
        documentHash: string;
        invoiceRef: string;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealId: BytesLike],
    [GulfFlowEscrowPolicy.DealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockDeal"
  ): TypedContractMethod<
    [
      dealId: BytesLike,
      supplier: AddressLike,
      invoiceRef: string,
      invoiceAmountUsdc6: BigNumberish,
      advanceAmountUsdc6: BigNumberish,
      documentHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseAdvance"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AdvanceReleased"
  ): TypedContractEvent<
    AdvanceReleasedEvent.InputTuple,
    AdvanceReleasedEvent.OutputTuple,
    AdvanceReleasedEvent.OutputObject
  >;
  getEvent(
    key: "DealCancelled"
  ): TypedContractEvent<
    DealCancelledEvent.InputTuple,
    DealCancelledEvent.OutputTuple,
    DealCancelledEvent.OutputObject
  >;
  getEvent(
    key: "DealCompleted"
  ): TypedContractEvent<
    DealCompletedEvent.InputTuple,
    DealCompletedEvent.OutputTuple,
    DealCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DealLocked"
  ): TypedContractEvent<
    DealLockedEvent.InputTuple,
    DealLockedEvent.OutputTuple,
    DealLockedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentsApproved"
  ): TypedContractEvent<
    DocumentsApprovedEvent.InputTuple,
    DocumentsApprovedEvent.OutputTuple,
    DocumentsApprovedEvent.OutputObject
  >;

  filters: {
    "AdvanceReleased(bytes32,address,uint256)": TypedContractEvent<
      AdvanceReleasedEvent.InputTuple,
      AdvanceReleasedEvent.OutputTuple,
      AdvanceReleasedEvent.OutputObject
    >;
    AdvanceReleased: TypedContractEvent<
      AdvanceReleasedEvent.InputTuple,
      AdvanceReleasedEvent.OutputTuple,
      AdvanceReleasedEvent.OutputObject
    >;

    "DealCancelled(bytes32)": TypedContractEvent<
      DealCancelledEvent.InputTuple,
      DealCancelledEvent.OutputTuple,
      DealCancelledEvent.OutputObject
    >;
    DealCancelled: TypedContractEvent<
      DealCancelledEvent.InputTuple,
      DealCancelledEvent.OutputTuple,
      DealCancelledEvent.OutputObject
    >;

    "DealCompleted(bytes32)": TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;
    DealCompleted: TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;

    "DealLocked(bytes32,address,address,string,uint256,uint256,bytes32)": TypedContractEvent<
      DealLockedEvent.InputTuple,
      DealLockedEvent.OutputTuple,
      DealLockedEvent.OutputObject
    >;
    DealLocked: TypedContractEvent<
      DealLockedEvent.InputTuple,
      DealLockedEvent.OutputTuple,
      DealLockedEvent.OutputObject
    >;

    "DocumentsApproved(bytes32,bytes32)": TypedContractEvent<
      DocumentsApprovedEvent.InputTuple,
      DocumentsApprovedEvent.OutputTuple,
      DocumentsApprovedEvent.OutputObject
    >;
    DocumentsApproved: TypedContractEvent<
      DocumentsApprovedEvent.InputTuple,
      DocumentsApprovedEvent.OutputTuple,
      DocumentsApprovedEvent.OutputObject
    >;
  };
}
